version: '3.8'

services:
  mysql_primary:
    image: mysql:8
    container_name: mysql_primary
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_primary
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3301:3306"
    volumes:
      - mysql_primary_data:/var/lib/mysql

  mysql_secondary:
    image: mysql:8
    container_name: mysql_secondary
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_secondary
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3302:3306"
    volumes:
      - mysql_secondary_data:/var/lib/mysql

  mysql_target:
    image: mysql:8
    container_name: mysql_target
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_target
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3303:3306"
    volumes:
      - mysql_target_data:/var/lib/mysql

volumes:
  mysql_primary_data:
  mysql_secondary_data:
  mysql_target_data:
